# Block 1: Handle all access from port 80 (HTTP) and redirect to HTTPS
server {
    listen 80;
    server_name jabick.site www.jabick.site;
    return 301 https://$host$request_uri;
}

# Block 2: Handle secure access on port 443 (HTTPS)
server {
    listen 443 ssl;
    server_name jabick.site www.jabick.site;

    # redirect Nginx to read SSL certificate
    ssl_certificate /etc/letsencrypt/live/jabick.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jabick.site/privkey.pem;

    # redirect data stream to Next.js
    location / {
        proxy_pass http://jabick:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}