server {
    listen 80;
    server_name _; # accept any IP or domain name

    location / {
        proxy_pass http://jabick:3000; # redirect data stream to the container named "jabick" on port 3000
        proxy_set_header Host $host; # set the host header to the host of the request
        proxy_set_header X-Real-IP $remote_addr;
    }
}